# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/TetsuOu"

[social.params]
icon = "Github"


[[social]]
identifier = "csdn"
name = "csdn"
url = "https://blog.csdn.net/qq_40889820"

[social.params]
icon = "csdn"
